### ISSUE TITLE
Stars and "See Also" display incorrectly on protected problem page

### ISSUE THREAD

**Issue by swwind** [sxyz-edu/user-scripts#2]
version: 0.3.0

e.g. <https://www.lydsy.com/JudgeOnline/show.php?id=1000>

Works fine on ordinary problem page.

**Comment by swwind** [comment]
所以是不是应该可以 merge 了

**Comment by sxyugao** [comment]
> 所以是不是应该可以 merge 了

alpha分支里的bzoj是个半成品啊。。除非你把你的LeanCloud部分去除掉

**Comment by swwind** [comment]
> > 所以是不是应该可以 merge 了
> 
> alpha分支里的bzoj是个半成品啊。。除非你把你的LeanCloud部分去除掉

我去填坑。。。
